#+OPTIONS: toc:nil num:nil
#+AUTHOR: Martin Fracker, ANTH 205-905 Spring 2017
#+LATEX_HEADER: \usepackage[margin=1in]{geometry}
#+LATEX_HEADER: \linespread{2}
#+TITLE: Restoring Trust in the Consulting Industry
It is important to find ways to remain competitive competitive in the IT
consulting industry, a business in which technical expertise has become more
important than domain knowledge, technology rapidly becomes obselete, and buying
engagements is common.

The IT consulting industry has certainly evolved over the years, from requiring
specific domain knowledge in addition to technical expertise to only requiring
techincal expertise and utilizing the client's onboarding process to become
familiar with the specifics of their domain. In Mr. Perry's case, who wished to
go into the business field as a software developer, he needed a business degree,
because business only hired software developers from business schools. The idea
was that if you wanted to build business software applications, you had to have
a business degree. Business software was also simpler back then. In many cases,
all they did was read and display information from a database and generate
reports. Today, as far as domain knowledge goes, as long as you have someone who
can explain the business rules, prior domain knowledge has become much less of a
necessity. Mr. Perry's theory is that software has gotten more complicated. So
much so, that computer science degrees and a good grasp on engineering practices
are required when applying for many software development positions.

This means, a background in ethical problem solving is necessary in the IT
consulting industry. Any engineering position, even if not public facing, would
still carry with it consequences that would affect the general public. For
example, an engineer who designed the latest rocketship for SpaceX greatly
affects the public when he decides to not pay as much attention as he should to
the pollution that the ship causes at launch even though the rocketship was
designed for use by a private company. Therefore, as the IT consulting industry
has shifted from a business discipline towards an engineering one, then
regardless of whether the client is public facing or not, it is important for
consultants in the field to have a background in ethical problem solving.

As an employee in the current IT consulting industry I can confirm that my role
is definitely one of engineering and it did not require prior domain knowledge.
The client I work for is in the business of providing risk management solutions
to agribusinesses. I knew nothing about the business before joining the project,
but I learn something new about their business with every meeting. Communicating
with the client on a frequent basis and gathering requirements from them is a
huge part of the job. The communication skills of an engineer are highly valued
as getting the client to voice their requirements is one thing, but translating
them properly is a whole different story.

Staying on top of technology and best practices in an industry where technology
rapidly becomes obselete is another challenge. Mr. Perry emphasized adopting an
attitude of life-long learning as a necessity for anyone in the consulting
industry. In the spirit of comitting to life-long learning Perry has always been
an early adopter of technologies and software development best practices. He
was, for example, an early adopter of the Agile approach to software
development. A decade ago, it was common for businesses to employ the Waterfall
method when designing and developing software, one that would ultimately result
in wasted time and headaches due to the stakeholders not playing an active role
in the development phase. Today much of the industry has
shifted to a more Agile approach to software development, one in which
stakeholders play a very active role in the development phase and provide a
constant feedback loop for the developers.

Staying on top of technology and best practices does not have to be something
only engineers in the IT consulting industry do. Other fields obviously
experience change in technology as well. An engineer can be thought of as a
mechanic who solves problem using the tools in his toolbox. Every couple of
years new and better tools will become available, and the engineers who adopt
them will be more effective than those who do not.

The IT Consulting Industry is a very competitive field, keeping up to date with
best-practices and rapidly changing technology is just one way to make sure you
stay competitive. Programming languages and methodologies are always changing.
Languages are constantly being extended with new features that accelerate
development, and methodologies are proposed that cope with the problems of those
that came before it. Not staying up to date means that you will not be as
efficient as the rest of the field and you will constantly be outbid by a
consultant who can do it more efficiently and therefore more cheaply.

Perhaps one of the more shocking challenges Perry mentioned with regards to the
competitive nature of the IT consulting industry was dealing with competitors
who engage in the practice of buying engagements. That is they bribe potential
clients to do business with them.
