#+OPTIONS: toc:nil num:nil
#+AUTHOR: Martin Fracker Section 905
#+LATEX_HEADER: \usepackage[margin=1in]{geometry}
#+TITLE: Week 5
* Week 5
The woodcutter was telling the truth. His final story is the one that sounded
least embellished and explained certain ubelievable elements of the stories that
everyone else told. For example, the bandit told about an honorable battle
between him and the husband. But, as the woodcutter told it, it actually seemed
quite lame and pitiful. You could also see what the Bandit meant about the
woman's fiery personality in the woodcutter's story. It seemed to me that
everything in the woodcutter's story was true for this reason.

Determining accountability is tough even after hearing the woodcutter's story.
Sure, the Bandit was the one who plunged the sword into the husband, but he was
also driven to it by the woman who provoked him, saying he had no backbone.
Neither the husband nor the woodcutter were innocent neither. The husband could
have been more understanding of the woman's state of mind after being raped, and
the woodcutter wanting to stay out of it did wrong by doing nothing to
intervene. This determination of accountability is what the Doing article
focuses on by taking an epistemographic approach to studying accountability in
engineering failures.
